In [92]:
import pandas as pd
import yfinance as yf

In [93]:
empresa = yf.Ticker("BBAS3.SA")

In [94]:
historico = empresa.history(period="1y")

In [95]:
historico.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-07-17 00:00:00-03:00,20.362297,20.420922,20.108257,20.264589,28673400,0.0,0.0
2025-07-18 00:00:00-03:00,20.127804,20.342760,19.736973,19.795597,42591900,0.0,0.0
2025-07-21 00:00:00-03:00,19.893303,19.942156,19.404764,19.404764,42352600,0.0,0.0
2025-07-22 00:00:00-03:00,19.531784,19.717430,19.414536,19.434076,24707100,0.0,0.0
2025-07-23 00:00:00-03:00,19.492700,19.951926,19.414534,19.746738,35932600,0.0,0.0

In [96]:
historico.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 251 entries, 2025-07-17 00:00:00-03:00 to 2026-07-17 00:00:00-03:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          251 non-null    float64
 1   High          251 non-null    float64
 2   Low           251 non-null    float64
 3   Close         251 non-null    float64
 4   Volume        251 non-null    int64
 5   Dividends     251 non-null    float64
 6   Stock Splits  251 non-null    float64
dtypes: float64(6), int64(1)
memory usage: 15.7 KB

In [97]:
historico.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,251.000000,251.000000,251.000000,251.000000,2.510000e+02,251.000000,251.0
mean,21.592753,21.877774,21.336928,21.591500,2.911696e+07,0.002190,0.0
std,1.938898,1.981518,1.889093,1.945217,1.692669e+07,0.017841,0.0
min,18.115023,18.476539,17.704647,17.929375,8.243200e+06,0.000000,0.0
25%,20.230395,20.407715,19.949404,20.166923,1.787785e+07,0.000000,0.0
50%,21.294979,21.501248,21.039595,21.290525,2.437270e+07,0.000000,0.0
75%,22.560165,22.917633,22.227523,22.441010,3.595315e+07,0.000000,0.0
max,27.255277,27.542484,27.017584,27.314697,1.318202e+08,0.220517,0.0

In [98]:
historico.shape

(251, 7)

In [99]:
historico.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits'], dtype='str')

In [100]:
historico.index

DatetimeIndex(['2025-07-17 00:00:00-03:00', '2025-07-18 00:00:00-03:00',
               '2025-07-21 00:00:00-03:00', '2025-07-22 00:00:00-03:00',
               '2025-07-23 00:00:00-03:00', '2025-07-24 00:00:00-03:00',
               '2025-07-25 00:00:00-03:00', '2025-07-28 00:00:00-03:00',
               '2025-07-29 00:00:00-03:00', '2025-07-30 00:00:00-03:00',
               ...
               '2026-07-06 00:00:00-03:00', '2026-07-07 00:00:00-03:00',
               '2026-07-08 00:00:00-03:00', '2026-07-09 00:00:00-03:00',
               '2026-07-10 00:00:00-03:00', '2026-07-13 00:00:00-03:00',
               '2026-07-14 00:00:00-03:00', '2026-07-15 00:00:00-03:00',
               '2026-07-16 00:00:00-03:00', '2026-07-17 00:00:00-03:00'],
              dtype='datetime64[s, America/Sao_Paulo]', name='Date', length=251, freq=None)

In [101]:
historico.isnull().sum()

Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

In [102]:
historico.duplicated().sum()

np.int64(0)

In [103]:
historico.dtypes

Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends       float64
Stock Splits    float64
dtype: object

In [104]:
import plotly.express as px

In [105]:
fig = px.line(
    historico,
    x=historico.index,
    y="Close",
    title="Preço de Fechamento da BBAS3 - Últimos 12 meses",
    labels={
        "x": "Data",
        "Close": "Preço de Fechamento (R$)"
    }
)

fig.show()